
server:
  port: 8080
  

spring:
  kafka:
    producer:
      bootstrap-servers:
      - localhost:9092
      client-id: kafka-microservices
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
      
    consumer:
      group-id: default-group-id
      bootstrap-servers:
      - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sgen
    password: 
  jpa:
    show-sql: true   
      
      
      

    
      
      